//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.serv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfParticipant", Namespace="http://tempuri.org/", ItemName="participant")]
    [System.SerializableAttribute()]
    public class ArrayOfParticipant : System.Collections.Generic.List<Chat.serv.participant> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="participant", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class participant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal idparticipantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pseudoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Chat.serv.Message[] MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal idparticipant {
            get {
                return this.idparticipantField;
            }
            set {
                if ((this.idparticipantField.Equals(value) != true)) {
                    this.idparticipantField = value;
                    this.RaisePropertyChanged("idparticipant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pseudo {
            get {
                return this.pseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.pseudoField, value) != true)) {
                    this.pseudoField = value;
                    this.RaisePropertyChanged("pseudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Chat.serv.Message[] Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal idmessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contenuField;
        
        private decimal idparticipantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Chat.serv.participant participantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal idmessage {
            get {
                return this.idmessageField;
            }
            set {
                if ((this.idmessageField.Equals(value) != true)) {
                    this.idmessageField = value;
                    this.RaisePropertyChanged("idmessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contenu {
            get {
                return this.contenuField;
            }
            set {
                if ((object.ReferenceEquals(this.contenuField, value) != true)) {
                    this.contenuField = value;
                    this.RaisePropertyChanged("contenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal idparticipant {
            get {
                return this.idparticipantField;
            }
            set {
                if ((this.idparticipantField.Equals(value) != true)) {
                    this.idparticipantField = value;
                    this.RaisePropertyChanged("idparticipant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Chat.serv.participant participant {
            get {
                return this.participantField;
            }
            set {
                if ((object.ReferenceEquals(this.participantField, value) != true)) {
                    this.participantField = value;
                    this.RaisePropertyChanged("participant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serv.sws_chatSoap")]
    public interface sws_chatSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudo de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Participer", ReplyAction="*")]
        Chat.serv.ParticiperResponse Participer(Chat.serv.ParticiperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Participer", ReplyAction="*")]
        System.Threading.Tasks.Task<Chat.serv.ParticiperResponse> ParticiperAsync(Chat.serv.ParticiperRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément ParticipantsResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Participants", ReplyAction="*")]
        Chat.serv.ParticipantsResponse Participants(Chat.serv.ParticipantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Participants", ReplyAction="*")]
        System.Threading.Tasks.Task<Chat.serv.ParticipantsResponse> ParticipantsAsync(Chat.serv.ParticipantsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément MessagesResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Messages", ReplyAction="*")]
        Chat.serv.MessagesResponse Messages(Chat.serv.MessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Messages", ReplyAction="*")]
        System.Threading.Tasks.Task<Chat.serv.MessagesResponse> MessagesAsync(Chat.serv.MessagesRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudo de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteParticipants", ReplyAction="*")]
        Chat.serv.DeleteParticipantsResponse DeleteParticipants(Chat.serv.DeleteParticipantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteParticipants", ReplyAction="*")]
        System.Threading.Tasks.Task<Chat.serv.DeleteParticipantsResponse> DeleteParticipantsAsync(Chat.serv.DeleteParticipantsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément message de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMessage", ReplyAction="*")]
        Chat.serv.InsertMessageResponse InsertMessage(Chat.serv.InsertMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Chat.serv.InsertMessageResponse> InsertMessageAsync(Chat.serv.InsertMessageRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudo de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getParticipantByPseudo", ReplyAction="*")]
        Chat.serv.getParticipantByPseudoResponse getParticipantByPseudo(Chat.serv.getParticipantByPseudoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getParticipantByPseudo", ReplyAction="*")]
        System.Threading.Tasks.Task<Chat.serv.getParticipantByPseudoResponse> getParticipantByPseudoAsync(Chat.serv.getParticipantByPseudoRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getParticipantByIdResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getParticipantById", ReplyAction="*")]
        Chat.serv.getParticipantByIdResponse getParticipantById(Chat.serv.getParticipantByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getParticipantById", ReplyAction="*")]
        System.Threading.Tasks.Task<Chat.serv.getParticipantByIdResponse> getParticipantByIdAsync(Chat.serv.getParticipantByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticiperRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Participer", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.ParticiperRequestBody Body;
        
        public ParticiperRequest() {
        }
        
        public ParticiperRequest(Chat.serv.ParticiperRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticiperRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo;
        
        public ParticiperRequestBody() {
        }
        
        public ParticiperRequestBody(string pseudo) {
            this.pseudo = pseudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticiperResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParticiperResponse", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.ParticiperResponseBody Body;
        
        public ParticiperResponse() {
        }
        
        public ParticiperResponse(Chat.serv.ParticiperResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticiperResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ParticiperResult;
        
        public ParticiperResponseBody() {
        }
        
        public ParticiperResponseBody(bool ParticiperResult) {
            this.ParticiperResult = ParticiperResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticipantsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Participants", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.ParticipantsRequestBody Body;
        
        public ParticipantsRequest() {
        }
        
        public ParticipantsRequest(Chat.serv.ParticipantsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ParticipantsRequestBody {
        
        public ParticipantsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticipantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParticipantsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.ParticipantsResponseBody Body;
        
        public ParticipantsResponse() {
        }
        
        public ParticipantsResponse(Chat.serv.ParticipantsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticipantsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chat.serv.ArrayOfParticipant ParticipantsResult;
        
        public ParticipantsResponseBody() {
        }
        
        public ParticipantsResponseBody(Chat.serv.ArrayOfParticipant ParticipantsResult) {
            this.ParticipantsResult = ParticipantsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Messages", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.MessagesRequestBody Body;
        
        public MessagesRequest() {
        }
        
        public MessagesRequest(Chat.serv.MessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MessagesRequestBody {
        
        public MessagesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.MessagesResponseBody Body;
        
        public MessagesResponse() {
        }
        
        public MessagesResponse(Chat.serv.MessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chat.serv.Message[] MessagesResult;
        
        public MessagesResponseBody() {
        }
        
        public MessagesResponseBody(Chat.serv.Message[] MessagesResult) {
            this.MessagesResult = MessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteParticipantsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteParticipants", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.DeleteParticipantsRequestBody Body;
        
        public DeleteParticipantsRequest() {
        }
        
        public DeleteParticipantsRequest(Chat.serv.DeleteParticipantsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteParticipantsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public DeleteParticipantsRequestBody() {
        }
        
        public DeleteParticipantsRequestBody(string pseudo, int id) {
            this.pseudo = pseudo;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteParticipantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteParticipantsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.DeleteParticipantsResponseBody Body;
        
        public DeleteParticipantsResponse() {
        }
        
        public DeleteParticipantsResponse(Chat.serv.DeleteParticipantsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteParticipantsResponseBody {
        
        public DeleteParticipantsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMessage", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.InsertMessageRequestBody Body;
        
        public InsertMessageRequest() {
        }
        
        public InsertMessageRequest(Chat.serv.InsertMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public InsertMessageRequestBody() {
        }
        
        public InsertMessageRequestBody(string message, int id) {
            this.message = message;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.InsertMessageResponseBody Body;
        
        public InsertMessageResponse() {
        }
        
        public InsertMessageResponse(Chat.serv.InsertMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertMessageResponseBody {
        
        public InsertMessageResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getParticipantByPseudoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getParticipantByPseudo", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.getParticipantByPseudoRequestBody Body;
        
        public getParticipantByPseudoRequest() {
        }
        
        public getParticipantByPseudoRequest(Chat.serv.getParticipantByPseudoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getParticipantByPseudoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo;
        
        public getParticipantByPseudoRequestBody() {
        }
        
        public getParticipantByPseudoRequestBody(string pseudo) {
            this.pseudo = pseudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getParticipantByPseudoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getParticipantByPseudoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.getParticipantByPseudoResponseBody Body;
        
        public getParticipantByPseudoResponse() {
        }
        
        public getParticipantByPseudoResponse(Chat.serv.getParticipantByPseudoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getParticipantByPseudoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getParticipantByPseudoResult;
        
        public getParticipantByPseudoResponseBody() {
        }
        
        public getParticipantByPseudoResponseBody(int getParticipantByPseudoResult) {
            this.getParticipantByPseudoResult = getParticipantByPseudoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getParticipantByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getParticipantById", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.getParticipantByIdRequestBody Body;
        
        public getParticipantByIdRequest() {
        }
        
        public getParticipantByIdRequest(Chat.serv.getParticipantByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getParticipantByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getParticipantByIdRequestBody() {
        }
        
        public getParticipantByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getParticipantByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getParticipantByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Chat.serv.getParticipantByIdResponseBody Body;
        
        public getParticipantByIdResponse() {
        }
        
        public getParticipantByIdResponse(Chat.serv.getParticipantByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getParticipantByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getParticipantByIdResult;
        
        public getParticipantByIdResponseBody() {
        }
        
        public getParticipantByIdResponseBody(string getParticipantByIdResult) {
            this.getParticipantByIdResult = getParticipantByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sws_chatSoapChannel : Chat.serv.sws_chatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sws_chatSoapClient : System.ServiceModel.ClientBase<Chat.serv.sws_chatSoap>, Chat.serv.sws_chatSoap {
        
        public sws_chatSoapClient() {
        }
        
        public sws_chatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sws_chatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sws_chatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sws_chatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chat.serv.ParticiperResponse Chat.serv.sws_chatSoap.Participer(Chat.serv.ParticiperRequest request) {
            return base.Channel.Participer(request);
        }
        
        public bool Participer(string pseudo) {
            Chat.serv.ParticiperRequest inValue = new Chat.serv.ParticiperRequest();
            inValue.Body = new Chat.serv.ParticiperRequestBody();
            inValue.Body.pseudo = pseudo;
            Chat.serv.ParticiperResponse retVal = ((Chat.serv.sws_chatSoap)(this)).Participer(inValue);
            return retVal.Body.ParticiperResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Chat.serv.ParticiperResponse> Chat.serv.sws_chatSoap.ParticiperAsync(Chat.serv.ParticiperRequest request) {
            return base.Channel.ParticiperAsync(request);
        }
        
        public System.Threading.Tasks.Task<Chat.serv.ParticiperResponse> ParticiperAsync(string pseudo) {
            Chat.serv.ParticiperRequest inValue = new Chat.serv.ParticiperRequest();
            inValue.Body = new Chat.serv.ParticiperRequestBody();
            inValue.Body.pseudo = pseudo;
            return ((Chat.serv.sws_chatSoap)(this)).ParticiperAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chat.serv.ParticipantsResponse Chat.serv.sws_chatSoap.Participants(Chat.serv.ParticipantsRequest request) {
            return base.Channel.Participants(request);
        }
        
        public Chat.serv.ArrayOfParticipant Participants() {
            Chat.serv.ParticipantsRequest inValue = new Chat.serv.ParticipantsRequest();
            inValue.Body = new Chat.serv.ParticipantsRequestBody();
            Chat.serv.ParticipantsResponse retVal = ((Chat.serv.sws_chatSoap)(this)).Participants(inValue);
            return retVal.Body.ParticipantsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Chat.serv.ParticipantsResponse> Chat.serv.sws_chatSoap.ParticipantsAsync(Chat.serv.ParticipantsRequest request) {
            return base.Channel.ParticipantsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Chat.serv.ParticipantsResponse> ParticipantsAsync() {
            Chat.serv.ParticipantsRequest inValue = new Chat.serv.ParticipantsRequest();
            inValue.Body = new Chat.serv.ParticipantsRequestBody();
            return ((Chat.serv.sws_chatSoap)(this)).ParticipantsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chat.serv.MessagesResponse Chat.serv.sws_chatSoap.Messages(Chat.serv.MessagesRequest request) {
            return base.Channel.Messages(request);
        }
        
        public Chat.serv.Message[] Messages() {
            Chat.serv.MessagesRequest inValue = new Chat.serv.MessagesRequest();
            inValue.Body = new Chat.serv.MessagesRequestBody();
            Chat.serv.MessagesResponse retVal = ((Chat.serv.sws_chatSoap)(this)).Messages(inValue);
            return retVal.Body.MessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Chat.serv.MessagesResponse> Chat.serv.sws_chatSoap.MessagesAsync(Chat.serv.MessagesRequest request) {
            return base.Channel.MessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Chat.serv.MessagesResponse> MessagesAsync() {
            Chat.serv.MessagesRequest inValue = new Chat.serv.MessagesRequest();
            inValue.Body = new Chat.serv.MessagesRequestBody();
            return ((Chat.serv.sws_chatSoap)(this)).MessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chat.serv.DeleteParticipantsResponse Chat.serv.sws_chatSoap.DeleteParticipants(Chat.serv.DeleteParticipantsRequest request) {
            return base.Channel.DeleteParticipants(request);
        }
        
        public void DeleteParticipants(string pseudo, int id) {
            Chat.serv.DeleteParticipantsRequest inValue = new Chat.serv.DeleteParticipantsRequest();
            inValue.Body = new Chat.serv.DeleteParticipantsRequestBody();
            inValue.Body.pseudo = pseudo;
            inValue.Body.id = id;
            Chat.serv.DeleteParticipantsResponse retVal = ((Chat.serv.sws_chatSoap)(this)).DeleteParticipants(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Chat.serv.DeleteParticipantsResponse> Chat.serv.sws_chatSoap.DeleteParticipantsAsync(Chat.serv.DeleteParticipantsRequest request) {
            return base.Channel.DeleteParticipantsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Chat.serv.DeleteParticipantsResponse> DeleteParticipantsAsync(string pseudo, int id) {
            Chat.serv.DeleteParticipantsRequest inValue = new Chat.serv.DeleteParticipantsRequest();
            inValue.Body = new Chat.serv.DeleteParticipantsRequestBody();
            inValue.Body.pseudo = pseudo;
            inValue.Body.id = id;
            return ((Chat.serv.sws_chatSoap)(this)).DeleteParticipantsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chat.serv.InsertMessageResponse Chat.serv.sws_chatSoap.InsertMessage(Chat.serv.InsertMessageRequest request) {
            return base.Channel.InsertMessage(request);
        }
        
        public void InsertMessage(string message, int id) {
            Chat.serv.InsertMessageRequest inValue = new Chat.serv.InsertMessageRequest();
            inValue.Body = new Chat.serv.InsertMessageRequestBody();
            inValue.Body.message = message;
            inValue.Body.id = id;
            Chat.serv.InsertMessageResponse retVal = ((Chat.serv.sws_chatSoap)(this)).InsertMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Chat.serv.InsertMessageResponse> Chat.serv.sws_chatSoap.InsertMessageAsync(Chat.serv.InsertMessageRequest request) {
            return base.Channel.InsertMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Chat.serv.InsertMessageResponse> InsertMessageAsync(string message, int id) {
            Chat.serv.InsertMessageRequest inValue = new Chat.serv.InsertMessageRequest();
            inValue.Body = new Chat.serv.InsertMessageRequestBody();
            inValue.Body.message = message;
            inValue.Body.id = id;
            return ((Chat.serv.sws_chatSoap)(this)).InsertMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chat.serv.getParticipantByPseudoResponse Chat.serv.sws_chatSoap.getParticipantByPseudo(Chat.serv.getParticipantByPseudoRequest request) {
            return base.Channel.getParticipantByPseudo(request);
        }
        
        public int getParticipantByPseudo(string pseudo) {
            Chat.serv.getParticipantByPseudoRequest inValue = new Chat.serv.getParticipantByPseudoRequest();
            inValue.Body = new Chat.serv.getParticipantByPseudoRequestBody();
            inValue.Body.pseudo = pseudo;
            Chat.serv.getParticipantByPseudoResponse retVal = ((Chat.serv.sws_chatSoap)(this)).getParticipantByPseudo(inValue);
            return retVal.Body.getParticipantByPseudoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Chat.serv.getParticipantByPseudoResponse> Chat.serv.sws_chatSoap.getParticipantByPseudoAsync(Chat.serv.getParticipantByPseudoRequest request) {
            return base.Channel.getParticipantByPseudoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Chat.serv.getParticipantByPseudoResponse> getParticipantByPseudoAsync(string pseudo) {
            Chat.serv.getParticipantByPseudoRequest inValue = new Chat.serv.getParticipantByPseudoRequest();
            inValue.Body = new Chat.serv.getParticipantByPseudoRequestBody();
            inValue.Body.pseudo = pseudo;
            return ((Chat.serv.sws_chatSoap)(this)).getParticipantByPseudoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chat.serv.getParticipantByIdResponse Chat.serv.sws_chatSoap.getParticipantById(Chat.serv.getParticipantByIdRequest request) {
            return base.Channel.getParticipantById(request);
        }
        
        public string getParticipantById(int id) {
            Chat.serv.getParticipantByIdRequest inValue = new Chat.serv.getParticipantByIdRequest();
            inValue.Body = new Chat.serv.getParticipantByIdRequestBody();
            inValue.Body.id = id;
            Chat.serv.getParticipantByIdResponse retVal = ((Chat.serv.sws_chatSoap)(this)).getParticipantById(inValue);
            return retVal.Body.getParticipantByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Chat.serv.getParticipantByIdResponse> Chat.serv.sws_chatSoap.getParticipantByIdAsync(Chat.serv.getParticipantByIdRequest request) {
            return base.Channel.getParticipantByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Chat.serv.getParticipantByIdResponse> getParticipantByIdAsync(int id) {
            Chat.serv.getParticipantByIdRequest inValue = new Chat.serv.getParticipantByIdRequest();
            inValue.Body = new Chat.serv.getParticipantByIdRequestBody();
            inValue.Body.id = id;
            return ((Chat.serv.sws_chatSoap)(this)).getParticipantByIdAsync(inValue);
        }
    }
}
